CREATE TABLE K012_ECT_CABINER(
K001_ID VARCHAR2(50) NOT NULL,
K012_ID VARCHAR2(50) NOT NULL,
K012_PARENT_ID VARCHAR2(50),
K012_TITLE VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX K012_PK_IDX ON K012_ECT_CABINER(K012_ID);

ALTER TABLE K012_ECT_CABINER ADD CONSTRAINT K012_TITLE_UK UNIQUE(K001_ID, K012_TITLE);

ALTER TABLE K012_ECT_CABINER ADD CONSTRAINT K012_PK PRIMARY KEY (K012_ID)
USING INDEX K012_PK_IDX;

CREATE OR REPLACE PACKAGE TEST_PKG
IS
	FUNCTION INSERT_DATA(P_K012_TITLE IN VARCHAR2) RETURN NUMBER;
    PROCEDURE INSERT_DATA_P(P_K012_TITLE IN VARCHAR2, P_ROW_COUNT OUT NUMBER);
END;

CREATE OR REPLACE PACKAGE BODY TEST_PKG
IS
	FUNCTION INSERT_DATA(P_K012_TITLE IN VARCHAR2) RETURN NUMBER
	IS
	BEGIN
		INSERT INTO K012_ECT_CABINER
		(K001_ID, K012_ID, K012_PARENT_ID, K012_TITLE)
		VALUES('777', SYS_GUID, NULL, P_K012_TITLE);
		RETURN SQL%ROWCOUNT;
	END;

	PROCEDURE INSERT_DATA_P(P_K012_TITLE IN VARCHAR2, P_ROW_COUNT OUT NUMBER)
	IS
    BEGIN
        INSERT INTO K012_ECT_CABINER
        (K001_ID, K012_ID, K012_PARENT_ID, K012_TITLE)
        VALUES('777', SYS_GUID, NULL, P_K012_TITLE);
        P_ROW_COUNT := SQL%ROWCOUNT;
    EXCEPTION
        WHEN OTHERS THEN
            IF INSTR(SQLERRM, 'K012_TITLE_UK') > 0 THEN
                P_ROW_COUNT := 0;
            ELSE
                RAISE;
            END IF;
    END;

END;

CREATE USER JAVA_TEST IDENTIFIED BY JAVA_TEST;

GRANT CREATE SESSION TO JAVA_TEST;

GRANT EXECUTE ON TEST_PKG TO JAVA_TEST;